#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Structural and style lint for the learning vault.

Every convention in the vault that is not checked here is a convention that rots.
The style rules live here and nowhere else: do not restate them in prose.

  uv run note_lint.py                    lint the whole vault, exit 1 on failure
  uv run note_lint.py <path> ...         lint specific notes
  uv run note_lint.py --hook             PostToolUse mode, reads JSON on stdin, exit 2
  uv run note_lint.py --links-only       only the wikilink checks (works on any vault)
  uv run note_lint.py --vault PATH       lint a different vault root
  uv run note_lint.py --todo             report open %%TODO%% markers
  uv run note_lint.py --unmeasured       report every 'needs measuring' row
  uv run note_lint.py --orphans          report notes no phase MOC links
  uv run note_lint.py --rough            report hand-written notes study has not shaped
"""

from __future__ import annotations

import json
import os
import pathlib
import re
import sys

REPO_HOME = pathlib.Path.home() / "personal"

TYPES = {"concept", "paper", "gate", "moc"}
PHASES = {"0", "1", "2", "3", "4", "5", "side"}
STATUS_BY_TYPE = {
    "concept": {"read", "implemented", "revised"},
    "paper": {"read", "implemented", "revised"},
    "gate": {"open", "passed"},
    "moc": {"read", "implemented", "revised"},
}
SECTIONS = {
    # concept and paper notes are his. He picks the headings, so nothing is
    # required. gate and moc are generated by this toolchain, so they keep a shape.
    "gate": [
        "## Gate",
        "## Metrics",
        "## How to reproduce",
        "## Attempts",
        "## What broke",
    ],
    "moc": ["## Gate", "## Reading", "## Notes", "## Status"],
}

WIKILINK = re.compile(r"\[\[([^\]|#]+)")
EMOJI = re.compile("[\U0001f300-\U0001faff\U00002600-\U000027bf\U0001f000-\U0001f0ff️❤]")
DASHES = re.compile("[—–]")
TODO = re.compile(r"%%\s*TODO")
NEEDS = "needs measuring"
NUMERIC = re.compile(r"^-?[0-9][0-9,._]*(e-?[0-9]+)?$")
BARE_NUMBER = re.compile(
    r"\b\d[\d,._]*\s*(GB/s|TB/s|TFLOPs?|GFLOPs?|FLOPs?|ms|us|ns|GiB|MiB|GB|MB|KB|tok/s|tokens/s|x)\b"
)
SOURCED = re.compile(r"(\]\(https?://|needs measuring|`)")
TRANSCRIPT = re.compile(
    r"\b(as we discussed|as discussed above|you asked|great question|let me |I'll |we'll |"
    r"in this conversation|as I mentioned)",
    re.IGNORECASE,
)


def frontmatter(text: str) -> dict[str, str]:
    """Minimal YAML front-matter reader. Only flat scalars and inline lists."""
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    out: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            continue
        if line[0] in " \t-":
            continue
        key, _, val = line.partition(":")
        out[key.strip()] = val.strip().strip('"').strip("'")
    return out


def section_body(text: str, head: str) -> str:
    out: list[str] = []
    on = False
    for line in text.splitlines():
        if line.strip() == head:
            on = True
            continue
        if on and line.startswith("## "):
            break
        if on:
            out.append(line)
    return "\n".join(out)


def spaced(stem: str) -> str:
    """The filename as he would type it inside a wikilink, case folded."""
    return stem.replace("-", " ").lower()


def titled(stem: str) -> str:
    return " ".join(w[:1].upper() + w[1:] for w in stem.split("-"))


def inline_list(raw: str) -> list[str]:
    raw = raw.strip()
    if raw.startswith("[") and raw.endswith("]"):
        raw = raw[1:-1]
    return [p.strip().strip('"').strip("'") for p in raw.split(",") if p.strip()]


NOTE_DIRS = ("side-tracks",)


def is_structured(p: pathlib.Path) -> bool:
    """A note study has already shaped. Rough hand-written files have no type."""
    return bool(
        frontmatter(p.read_text(encoding="utf-8", errors="replace")).get("type")
    )


def is_note_path(p: pathlib.Path, root: pathlib.Path) -> bool:
    """Notes live under Phase N/ or side-tracks/. Root files are the spine, not notes."""
    parts = p.relative_to(root).parts
    if len(parts) < 2:
        return False
    return parts[0].startswith("Phase ") or parts[0] in NOTE_DIRS


class Vault:
    def __init__(self, root: pathlib.Path):
        self.root = root
        self.notes = sorted(
            p
            for p in root.rglob("*.md")
            if ".git" not in p.parts
            and not any(part.startswith(".") for part in p.relative_to(root).parts[:-1])
        )
        self.targets: dict[str, pathlib.Path] = {}
        self.dupes: dict[str, list[pathlib.Path]] = {}
        for p in self.notes:
            stem = p.name[:-3]
            if stem in self.targets:
                self.dupes.setdefault(stem, [self.targets[stem]]).append(p)
            self.targets[stem] = p
        self.attachments: set[str] = {
            f.name
            for f in root.rglob("*")
            if f.is_file()
            and f.suffix.lower()
            in (".png", ".svg", ".jpg", ".jpeg", ".gif", ".webp", ".pdf")
            and ".git" not in f.parts
        }
        self.aliases: dict[str, pathlib.Path] = {}
        for p in self.notes:
            fm = frontmatter(p.read_text(encoding="utf-8", errors="replace"))
            for a in inline_list(fm.get("aliases", "")):
                self.aliases[a] = p

    def resolves(self, target: str) -> bool:
        t = target.strip()
        return (
            t in self.targets
            or t in self.aliases
            or t in self.attachments
            or (self.root / t).exists()
        )

    def moc_links(self) -> dict[str, list[pathlib.Path]]:
        """Wikilink targets under '## Notes' or '## Gate' of every phase MOC."""
        found: dict[str, list[pathlib.Path]] = {}
        for p in self.notes:
            if not re.fullmatch(r"phase-\d|side-tracks", p.name[:-3]):
                continue
            text = p.read_text(encoding="utf-8", errors="replace")
            body = section_body(text, "## Notes") + "\n" + section_body(text, "## Gate")
            for m in WIKILINK.finditer(body):
                found.setdefault(m.group(1).strip(), []).append(p)
        return found


def check_note(
    path: pathlib.Path, v: Vault, moc: dict[str, list[pathlib.Path]]
) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    fm = frontmatter(text)
    errs: list[str] = []
    rel = path.relative_to(v.root)
    stem = path.name[:-3]

    if not fm.get("type"):
        return []  # his own structure, which is the default. Nothing restructures it.

    ntype = fm.get("type", "")
    if ntype not in TYPES:
        errs.append(f"type must be one of {sorted(TYPES)}, got {ntype!r}")

    phase = fm.get("phase", "")
    if phase not in PHASES:
        errs.append(f"phase must be one of {sorted(PHASES)}, got {phase!r}")
    else:
        top = rel.parts[0]
        want = f"Phase {phase}" if phase != "side" else "side-tracks"
        if len(rel.parts) > 1 and top != want:
            errs.append(
                f"phase: {phase} but the note sits under {top!r}, expected {want!r}"
            )

    status = fm.get("status", "")
    if ntype in STATUS_BY_TYPE and status not in STATUS_BY_TYPE[ntype]:
        errs.append(f"status {status!r} invalid for type {ntype!r}")

    if ntype in ("concept", "paper", "moc"):
        als = inline_list(fm.get("aliases", ""))
        want = spaced(stem)
        if not als:
            errs.append(
                f"aliases is empty. Add {want!r} at least, or [[{titled(stem)}]] "
                f"resolves to nothing."
            )
        elif want not in {a.strip().lower() for a in als}:
            errs.append(
                f"no alias matches {want!r}, so [[{titled(stem)}]] will not resolve. "
                f"Filenames here are kebab-case and wikilinks get typed with spaces."
            )

    if ntype in ("concept", "paper"):
        if not fm.get("source", "").startswith("http") and status != "read":
            errs.append("source must be a URL before status leaves 'read'")
        if status in ("implemented", "revised"):
            code = fm.get("code", "")
            if not code or code in ("null", "~"):
                errs.append(
                    f"status is {status} but code: is empty. Point at the real file."
                )
            elif not (REPO_HOME / code).exists():
                errs.append(
                    f"code: {code} does not exist under {REPO_HOME}. It moved or got renamed."
                )
    if status == "revised" and not re.fullmatch(
        r"\d{4}-\d{2}-\d{2}", fm.get("revised", "")
    ):
        errs.append("status is revised but revised: is not a YYYY-MM-DD date")
    if (
        ntype == "gate"
        and status == "passed"
        and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", fm.get("passed", ""))
    ):
        errs.append("gate is passed but passed: is not a YYYY-MM-DD date")

    follows = fm.get("follows", "")
    if follows:
        tgt = follows.strip().lstrip("[").rstrip("]")
        if not v.resolves(tgt):
            errs.append(f"follows: [[{tgt}]] does not resolve")

    if stem in v.dupes:
        others = ", ".join(str(p.relative_to(v.root)) for p in v.dupes[stem])
        errs.append(
            f"basename {stem!r} is not unique ({others}). newLinkFormat shortest breaks."
        )

    for head in SECTIONS.get(ntype, []):
        if head not in text:
            errs.append(f"missing required section: {head}")
    order = [h for h in SECTIONS.get(ntype, []) if h in text]
    positions = [text.index(h) for h in order]
    if positions != sorted(positions):
        errs.append("required sections are out of template order")

    if ntype in ("concept", "paper", "gate"):
        owners = moc.get(stem, [])
        alias_hits = [a for a in inline_list(fm.get("aliases", "")) if a in moc]
        if not owners and not alias_hits:
            errs.append(
                "no phase MOC links this note under '## Notes'. It is an orphan."
            )
        elif len(owners) > 1:
            names = ", ".join(p.name for p in owners)
            errs.append(
                f"linked from more than one MOC ({names}). Exactly one owns it."
            )

    errs += check_metrics(text, ntype, status)
    errs += check_style(text, status)
    return errs


def check_metrics(text: str, ntype: str, status: str) -> list[str]:
    head = "## Metrics" if ntype == "gate" else "## What does it cost?"
    body = section_body(text, head)
    if not body.strip():
        return []
    unmeasured = 0
    errs: list[str] = []
    for line in body.splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if (
            len(cells) < 4
            or cells[0].lower() in ("metric", "quantity")
            or set(cells[0]) <= {"-", ":"}
        ):
            continue
        _, value, unit, command = cells[0], cells[1], cells[2], cells[3]
        if value == NEEDS:
            unmeasured += 1
            if unit != "-" or command != "-":
                errs.append(
                    f"'{NEEDS}' row must have '-' for unit and command: {line.strip()}"
                )
        elif NUMERIC.match(value):
            if not unit or unit == "-":
                errs.append(f"numeric value with no unit: {line.strip()}")
            if not command or command == "-":
                errs.append(
                    f"numeric value with no command that produced it: {line.strip()}"
                )
        elif value:
            errs.append(
                f"value must be a number or the literal '{NEEDS}': {line.strip()}"
            )
    if ntype == "gate" and status == "passed" and unmeasured:
        errs.append(f"gate claims passed with {unmeasured} '{NEEDS}' row(s)")
    return errs


def check_style(text: str, status: str) -> list[str]:
    errs: list[str] = []
    metrics = section_body(text, "## What does it cost?") + section_body(
        text, "## Metrics"
    )
    for i, line in enumerate(text.splitlines(), 1):
        if EMOJI.search(line):
            errs.append(f"L{i}: emoji")
        if DASHES.search(line):
            errs.append(f"L{i}: em dash or en dash. Use a hyphen or a colon.")
        if TODO.search(line) and status == "revised":
            errs.append(f"L{i}: open %%TODO%% in a note marked revised")
        if TRANSCRIPT.search(line):
            errs.append(
                f"L{i}: transcript voice. The note is not a record of the conversation."
            )
        m = BARE_NUMBER.search(line)
        if (
            m
            and line not in metrics
            and not SOURCED.search(line)
            and not line.strip().startswith("|")
        ):
            errs.append(
                f"L{i}: number '{m.group(0)}' with no source. Cite it, put it in the metrics "
                f"table with a command, or write 'needs measuring'."
            )
    return errs


def check_links(v: Vault) -> list[tuple[pathlib.Path, int, str]]:
    bad: list[tuple[pathlib.Path, int, str]] = []
    for p in v.notes:
        for i, line in enumerate(
            p.read_text(encoding="utf-8", errors="replace").splitlines(), 1
        ):
            if line.lstrip().startswith(("```", "    ")):
                continue
            for m in WIKILINK.finditer(line):
                t = m.group(1).strip()
                if not v.resolves(t):
                    bad.append((p, i, t))
    return bad


def main() -> int:
    argv = sys.argv[1:]
    root = pathlib.Path(
        os.environ.get("CLAUDE_PROJECT_DIR") or "/Users/samit/personal/learning"
    ).resolve()
    # --vault takes a value, and that value is not a note to lint. Without pulling
    # it out, `--vault X` used to land in `explicit`, match no .md, and exit 0
    # having checked nothing at all.
    consumed: set[int] = set()
    if "--vault" in argv:
        i = argv.index("--vault")
        if i + 1 >= len(argv):
            print("--vault needs a path", file=sys.stderr)
            return 2
        root = pathlib.Path(argv[i + 1]).resolve()
        consumed.add(i + 1)

    hook = "--hook" in argv
    explicit: list[pathlib.Path] = []
    if hook:
        try:
            data = json.load(sys.stdin)
        except json.JSONDecodeError:
            return 0
        ti = data.get("tool_input") or {}
        cands = [ti.get("file_path")] + [
            e.get("file_path") for e in (ti.get("edits") or [])
        ]
        explicit = [pathlib.Path(c) for c in cands if c]
    else:
        explicit = [
            pathlib.Path(a).resolve()
            for n, a in enumerate(argv)
            if not a.startswith("--") and n not in consumed
        ]

    v = Vault(root)

    if "--links-only" in argv:
        bad = check_links(v)
        for p, i, t in bad:
            print(f"{p.relative_to(root)}:{i}: unresolved [[{t}]]")
        print(f"\n{len(bad)} unresolved wikilinks across {len(v.notes)} notes")
        return 1 if bad else 0

    moc = v.moc_links()

    if "--orphans" in argv:
        n = 0
        for p in v.notes:
            fm = frontmatter(p.read_text(encoding="utf-8", errors="replace"))
            if fm.get("type") not in ("concept", "paper", "gate"):
                continue
            stem = p.name[:-3]
            if stem not in moc and not any(
                a in moc for a in inline_list(fm.get("aliases", ""))
            ):
                print(f"orphan: {p.relative_to(root)}")
                n += 1
        print(f"\n{n} orphans")
        return 1 if n else 0

    if "--aliases" in argv:
        n = 0
        for p in v.notes:
            if not is_note_path(p, root):
                continue
            stem = p.name[:-3]
            fm = frontmatter(p.read_text(encoding="utf-8", errors="replace"))
            als = {a.strip().lower() for a in inline_list(fm.get("aliases", ""))}
            if spaced(stem) in als:
                continue
            print(f"{p.relative_to(root)}: [[{titled(stem)}]] resolves to nothing. "
                  f"Add   aliases: [{titled(stem)}, {spaced(stem)}]")
            n += 1
        print(f"\n{n} note(s) a spaced wikilink cannot reach")
        return 1 if n else 0

    if "--rough" in argv:
        n = 0
        for p in v.notes:
            if is_note_path(p, root) and not is_structured(p):
                print(f"no front matter, so unindexed: {p.relative_to(root)}")
                n += 1
        print(f"\n{n} notes with no front matter. Fine, just unindexed.")
        return 0

    if "--todo" in argv:
        for p in v.notes:
            for i, line in enumerate(
                p.read_text(encoding="utf-8", errors="replace").splitlines(), 1
            ):
                if TODO.search(line):
                    print(f"{p.relative_to(root)}:{i}: {line.strip()}")
        return 0

    if "--unmeasured" in argv:
        for p in v.notes:
            for i, line in enumerate(
                p.read_text(encoding="utf-8", errors="replace").splitlines(), 1
            ):
                if NEEDS in line:
                    print(f"{p.relative_to(root)}:{i}: {line.strip()}")
        return 0

    if explicit:
        targets = [
            p
            for p in explicit
            if p.suffix == ".md"
            and p.exists()
            and p in v.notes
            and is_note_path(p, v.root)
            and is_structured(p)
        ]
        if not targets:
            return 0
    else:
        targets = [p for p in v.notes if is_note_path(p, v.root) and is_structured(p)]

    failed = False
    for p in targets:
        errs = check_note(p, v, moc)
        bad_links = [
            (i, t)
            for i, line in enumerate(
                p.read_text(encoding="utf-8", errors="replace").splitlines(), 1
            )
            for t in (m.group(1).strip() for m in WIKILINK.finditer(line))
            if not v.resolves(t)
        ]
        errs += [f"L{i}: unresolved [[{t}]]" for i, t in bad_links]
        if errs:
            failed = True
            print(f"note_lint FAILED {p.relative_to(root)}", file=sys.stderr)
            for e in errs:
                print(f"  {e}", file=sys.stderr)
    if failed:
        print("\nFix the note. Do not edit the lint.", file=sys.stderr)
        return 2 if hook else 1
    if not hook:
        print(f"note_lint clean: {len(targets)} notes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
